### ISSUE TITLE
Entities Values not Updating

### ISSUE THREAD

**Issue by Tyfosho** [JohNan/home-assistant-plaato#6]
I have the integration set to the default value of 5 mins between updates, however it's been over 5 mins and none of my entities appear to be updating. 

https://imgur.com/a/H1qInkh

**Comment by JohNan** [comment]
I might have found a possible reason for this. Stay tuned.

**Comment by JohNan** [comment]
Fixed by https://github.com/JohNan/home-assistant-plaato/pull/10

**Comment by Tyfosho** [comment]
@JohNan - I downloaded the latest build, deleted all the files from custom_components, and removed and re-added the integration. Are there any other steps I need to do to reinstall?

My entities still appear to not be updating regularly, and if I click on "Options" on the integration it just says "Please wait while the integration is installed" with a spinning circle.

**Comment by JohNan** [comment]
@Tyfosho thank you for the information. My PR to Core was accepted and merged last week. I will also update the custom component with the latest code. Hopefully that will solve the issue.

**Comment by JohNan** [comment]
Should hopefully be fixed in the latest release: [1.2.6](https://github.com/JohNan/home-assistant-plaato/releases/tag/v1.2.6)
